# Python 机器学习

## 1. Numpy 入门

### 1.1 数组基础

- Numpy 相较于 Python 列表，计算速度大大增加，代码也更加简洁，可以明显看出在进行大量数据计算时 Numpy 具有明显优势：

In [1]:
%%timeit

# 使用传统方式计算
list_a = [1, 2, 3, 123, 456, 789, 222, 333, 555, 888]
list_b = [4, 5, 6, 123, 241, 159, 124, 168, 854, 235]
list_c = []

for i in range(len(list_a)):
    list_c.append(list_a[i] + list_b[i])

5.79 μs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%%timeit

# 使用 Numpy 数组计算
import numpy as np

array_a = np.array([1, 2, 3, 123, 456, 789, 222, 333, 555, 888])
array_b = np.array([1, 2, 3, 123, 456, 789, 222, 333, 555, 888])
array_c = array_a + array_b

4.73 μs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### 1.1.1 创建一个 Numpy 数组

1. 从 Python 元组或列表创建，使用 '''np.array()''' 函数进行创建：

In [5]:
import numpy as np

# 创建一维数组
list_data = [1, 2, 3, 4, 5]
array_1d = np.array(list_data)

print("一维数组:\n")
print(array_1d)

# 创建二维数组
list_2d_data = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d_data)

print("\n二维数组:\n")
print(array_2d)

一维数组:

[1 2 3 4 5]

二维数组:

[[1 2 3]
 [4 5 6]]
